### ISSUE TITLE
GRNBoost2 not available in R 4.0?

### ISSUE THREAD

**Issue by mr-september** [aertslab/GRNBoost#7]
Hi, I couldn't find a dedicated Github for GRNBoost2 - is it still supported in this Github? 

Anyway, trying to install (through Biocmanager) on Rstudio gives this error
```
Warning message:
package ‘GRNBoost2’ is not available (for R version 4.0.2) 
```
is this something users can circumvent (without reverting to R 3 and causing other incompatibility issues)?

**Comment by cflerin** [comment]
Hi @mr-september ,

You can find the repo for GRNBoost2 at https://github.com/tmoerman/arboreto. It's a Python package so you won't be able to use it with R directly, but you can import the results from GRNBoost2 into R. Arboreto is also installed as part of the pySCENIC package (https://github.com/aertslab/pySCENIC). If you want to keep everything in R, you could use the GENIE3 method for GRN inference (`BiocManager::install(c("GENIE3"))`).
